### ISSUE TITLE
Android 6.0 "Auto Backup" : Security considerations

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#146]
Since API 23 is released, it is now (very) easy to implement "Auto Backup" for hosts, keys and config on  Google Drive (with encryption).
From what I see, we can't let the user decide if he want to backup or not his data to Drive.
I personally like the idea of having all my data restored when I flash a new ROM or buy a new device, and I'm not too afraid of Google Drive.
ConnectBot data may be very sensitive, so other users may think otherwise.

ref : http://developer.android.com/preview/backup/index.html?utm_campaign=autobackup-729&utm_source=dac&utm_medium=blog

**Comment by jklein24** [comment]
+1 - I think auto backup would be pretty sweet, but we might want it as opt-in instead of on by default. Maybe we could prompt the user the first time they use the app asking if they want to enable it (similar to what some apps do with analytics opt-in). As you mentioned, we'll also need to thing about which data is OK to sync in general for security reasons.

**Comment by jklein24** [comment]
It seems like maybe we could let the user decide whether to backup his/her data by optionally storing data in the NoBackupFilesDir:

```
Automatically excluded:
Not all app data should be backed up, such as temporary files and caches, so the automatic backup service excludes certain data files by default:

- Files in the directories referred to by the getCacheDir() and getCodeCacheDir() methods.
- Files located on external storage, unless they reside in the directory referred to by the getExternalFilesDir() method.
- Files located in the directory referred to by the getNoBackupFilesDir() method.
```

**Comment by jklein24** [comment]
cc: @bengolds

**Comment by bengolds** [comment]
I don't actually think we need to worry about this. The app data backup is a system-level setting; if the user doesn't want their app data backed up then they turn that off at the system level.

**Comment by alescdb** [comment]
Users may still want to backup other apps, but may not want to backup their private keys to Drive (especially if they are not password protected).
This is only a guess, I think Drive (with two-factor auth) is more safe than a phone :-)

**Comment by fat-tire** [comment]
Automatically sending ssh keys to the cloud by default is nuts, IMO.  Especially since this is opt-out and happening in the background and without the user's knowledge.  How would someone know to shut this off system wide unless they were REALLY paying attention?!

Why is this even being discussed?  Any kind of auto forwarding of ssh keys to the cloud should be disabled and an update sent to the play store... before Marshmallow is released.

The fix is simple, according to the link in the OP:

    <app ...
        android:allowBackup="false">
    </app>

**Comment by tornewuff** [comment]
Full-data backup is only enabled for applications that have been updated to target M, specifically to give developers the opportunity to disable backup if it's not appropriate, so there's no rush to do this urgently before M is released, it just needs to be looked at alongside any other M changes when updating the targetSDK.

**Comment by fat-tire** [comment]
I think you might be right about the targetSDK-- though it's not listed as a requirement anywhere in the description.  Instead, it says:

> Devices running the Android M Preview system help ensure a good experience for users in these circumstances by automatically backing up app data to Google Drive.

and

>Automatic backups are enabled for all apps installed on devices running the Android M Preview. No additional app code is required.~~

To me the above reads like it's enabled for all apps running on Android M, regardless of what they're targeting.  It does also mention that if the backup legacy service is being used, that it will continue to function.   That may apply to CB due to the line:

     		android:backupAgent=".service.BackupAgent"

...but again, it's not clear.  It's only when I watched [this video](https://www.youtube.com/watch?t=184&v=HXacyy0HSW0) carefully that it seems M must be targeted specifically, at least for the preview.  (I had also been wondering how it would know what to save once the app has more than 25MB of data--- if I'm hearing it right, it *sounds like* the backup process won't back up anything if there's more than 25MB.  But I'm not completely sure.)

Hmf.  The documentation could definitely be clearer and more complete.

**Comment by dkaparis** [comment]
What is the status on this issue? I just noticed that my defined hosts together with on-device private keys got replicated to a new Android Marshmallow device I installed Connectbot 1.8.6 on.

**Comment by tornewuff** [comment]
So just to be clear: M did not change anything here, because ConnectBot already has a backup agent, and so full data backup will not be used, no matter what.

ConnectBot has *always* backed up all its data (including private keys) via the backup agent, on any OS version with backup enabled systemwide. It should probably be clearer about this, and allow it to be disabled (see #351 for that I guess, since it's already filed) - but there's no issue here with the new backup facilities in M.

**Comment by fat-tire** [comment]
@tornewuff putting notification to the user/allowing them to opt-out aside as a separate issue (#351) , can you explain why do you think uploading private keys should be the expected default behavior?  What SSH client includes off-device private key backup?  Especially one that doesn't use SSH itself for the transport mechanism, and uses a completely unknown encryption method overseen entirely by a third party?  Makes no sense to me.

**Comment by tornewuff** [comment]
Whether it should be the default is also #351 - that is the title of that issue. This bug was filed about concerns with changes to the backup system in android 6.0, and that's resolved - the changes do not affect connectbot.
