### ISSUE TITLE
hostmask does not allow hostnames with underscores

### ISSUE THREAD

**Issue by garrison** [connectbot/connectbot#188]
`hostmask` (as defined [here](https://github.com/connectbot/connectbot/blob/ad15d09a0734adc07324cba10527407c91c3d9b5/app/src/main/java/org/connectbot/transport/SSH.java#L104) and [here](https://github.com/connectbot/connectbot/blob/b0bea6930e0539a3b1fe07672499bdc91eb84cd8/app/src/main/java/org/connectbot/transport/Telnet.java#L70)) does not match hostnames that contain underscores.  Because of this, it is currently impossible to `ssh` to a hostname that contains underscores without manually looking up the IP address and typing that in instead.

There may be other similarly valid characters that are also not matched by the regular expression, too.

**Comment by kruton** [comment]
RFC 952 and RFC 1123 still dictate you can't have an underscore in a host name. Is this for a Windows machine or something?

**Comment by garrison** [comment]
Thanks for the info, which I was clearly unaware of.  In my case, my network hostname at work was chosen by the previous user of the machine, and it contains an underscore.  The network administrator refuses to change a hostname once it has been registered on the network, so the name of this machine on the internet (given via DHCP) violates these RFCs.  I find it hard to imagine I have the only such hostname in the wild, but feel free to mark as invalid if you see fit.

**Comment by garrison** [comment]
Note also that the current regular expression also prevents underscores (and other characters) in the domain name, not just the hostname.  So it is incorrect anyway.

**Comment by Derkades** [comment]
Underscores are valid in domain names: https://stackoverflow.com/a/2183140

**Comment by brianjmurrell** [comment]
I think this comes down to the difference between what the _rules_ say and what is commonly being done in the real world.

The reality is that lots of people are using _ in hostnames and it's being accepted and nothing is breaking as a result of it.

It's so widespread as to be impractical to have everyone walk it back now.

So can Connect embrace the robustness principle and be practical rather than trying to be an enforcer of a wildly violated for that is having no negative consequence?

What do we have to do to turn this discussion into an issue to be fixed?
