### ISSUE TITLE
When opening pubkey generation view, keyboard is immediately being displayed and hides some options, essentially making them invisible at first glance

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#212]
Hello,

when opening the pubkey generation view, the cursor immediately and automatically jumps to the "Nickname:" field and opens the keyboard, which is then hiding some options, which essentially makes them invisible at first glance (slightly depending on the keyboard height).

Could you please fix that by making the cursor not jump automatically to the "Nickname:" field when opening the pubkey generation view?

Regards

**Comment by rhansby** [comment]
I believe it is fine as is. The keyboard does block lower items, but it is very intuitive (and necessary) to scroll down in order to complete the action. See my below screenshots:

![pubkey keyboard](https://cloud.githubusercontent.com/assets/1788374/9920357/45b6faba-5c88-11e5-989c-caa8f0b4cbdb.png)

![pubkey keyboard 2](https://cloud.githubusercontent.com/assets/1788374/9920358/4870c704-5c88-11e5-8e81-80d8a50f49a7.png)

**Comment by rhansby** [comment]
@jklein24 or @kruton please weigh in on this and/or close it.

**Comment by jklein24** [comment]
I agree that this isn't really a big deal.
