### ISSUE TITLE
Mouse-based selection of text

### ISSUE THREAD

**Issue by bengolds** [connectbot/connectbot#232]
Click-dragging on text with a mouse should give the user a way to select that text. Jeremy, I remember you had thoughts on the exact way we wanted to implement this.

**Comment by jklein24** [comment]
Right now on head, clicking and dragging does select and copy automatically. However, it does so in the same "block select" mode as copy otherwise in the app. It would be much nicer to have text selection work like a TextView. @alescdb has this mostly working in https://github.com/connectbot/connectbot/pull/129, but it needs a few fixes and finishing. @alescdb, do you have any time to take another stab at that? If not, I can take what you've done and see if I can finish it off.

**Comment by jklein24** [comment]
@rhansby is checking out fixing #129 and making it ship-able. @alescdb, please talk to him if you still want to finish it yourself instead or if you have any pointers along the way.

**Comment by alescdb** [comment]
@jklein24 , I just had my second baby girl recently, my (free) time is very limited right now. My wife will kill me if she sees me more than 2 minutes in front of my computer :-)
Anyone can take over if they want. My last thought was to adapt android.widget.Editor on TerminalView this may be a better and simpler way.

**Comment by jklein24** [comment]
Congratulations, @alescdb! We'll be sure to at least cc you on the PRs to keep you in the loop ☺.
