### ISSUE TITLE
Discussion: primary and accent colors

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#256]
(I've opened this new issue to extend off of discussion in #167)

Colors are taken from https://www.google.com/design/spec/style/color.html#

I've taken a few screenshots of possible primary/accent color combinations. Please discuss what is good/bad about them. Also feel free to request more sample color combos / screenshots.

Primary | Accent | Hosts View | Settings View
------------- | ------------- | ------------- | -------------
Cyan  | Deep Orange | ![cyan orange hosts](https://cloud.githubusercontent.com/assets/1788374/10081995/7977b626-62ac-11e5-8639-a1ca6793a04a.png) | ![cyan orange settings](https://cloud.githubusercontent.com/assets/1788374/10082009/82cb6bdc-62ac-11e5-9646-a6eb1143f40d.png)
Cyan  | Cyan | ![hosts](https://cloud.githubusercontent.com/assets/1788374/10082043/b6221efe-62ac-11e5-976b-2fe9218d27a1.png) | ![settings](https://cloud.githubusercontent.com/assets/1788374/10082054/bf42ef22-62ac-11e5-8482-fb15946285ea.png)
Cyan  | Light Blue | ![hosts](https://cloud.githubusercontent.com/assets/1788374/10082127/122e4a74-62ad-11e5-9e5c-01194b7fff78.png) | ![settings](https://cloud.githubusercontent.com/assets/1788374/10082128/13bd88e6-62ad-11e5-991a-f88470ac6668.png)
Cyan | Light Blue (lightened) | ![hosts](https://cloud.githubusercontent.com/assets/1788374/10082750/2b36cbce-62b0-11e5-9fe6-40e3c6ad9d27.png) | ![setting](https://cloud.githubusercontent.com/assets/1788374/10082786/524f1ea0-62b0-11e5-9e14-55332124bcd5.png)
Light Blue  | Blue | ![hosts](https://cloud.githubusercontent.com/assets/1788374/10082171/49c29cec-62ad-11e5-9dc2-6dc3b8a7db95.png) | ![settings](https://cloud.githubusercontent.com/assets/1788374/10082173/4cc0c856-62ad-11e5-8415-bacc36bcc3ce.png)
Light Blue  | Light Blue | ![hosts](https://cloud.githubusercontent.com/assets/1788374/10082176/517eb920-62ad-11e5-8d79-899ba79ab290.png) | ![settings](https://cloud.githubusercontent.com/assets/1788374/10082177/5305619a-62ad-11e5-9e89-98d4ee5435af.png)
Light Blue  | Light Blue (lightened) | ![hosts](https://cloud.githubusercontent.com/assets/1788374/10082200/71635eee-62ad-11e5-82b5-0039d5d23b96.png) | ![settings](https://cloud.githubusercontent.com/assets/1788374/10082203/736a6aa2-62ad-11e5-86db-db4bd3da452d.png)
Light Blue | Light Blue (slightly lightened) | ![hosts](https://cloud.githubusercontent.com/assets/1788374/10083167/064a82d6-62b2-11e5-8725-44f18b49df18.png) | ![settings](https://cloud.githubusercontent.com/assets/1788374/10083169/09781752-62b2-11e5-818b-8fedcb914cdf.png)
Light Blue  | Teal | ![hosts](https://cloud.githubusercontent.com/assets/1788374/10082210/7967556e-62ad-11e5-9f00-444ef26f97f4.png) | ![settings](https://cloud.githubusercontent.com/assets/1788374/10082214/7c8da2a2-62ad-11e5-99fe-0073e65a42ff.png)

**Comment by jklein24** [comment]
cc @bengolds.

Thanks for fleshing out all the options, @rhansby!!
My vote is for Light Blue + Light Blue lightened or Cyan + light blue lightened.

**Comment by jklein24** [comment]
Logo for reference 
![image](https://cloud.githubusercontent.com/assets/1393755/10082509/f001940e-62ae-11e5-835e-9dd0500d0b32.png)

**Comment by rhansby** [comment]
(added a cyan + light blue (lightened) sample)

**Comment by rhansby** [comment]
(added a light blue + light blue (slightly lightened) sample)

**Comment by jklein24** [comment]
OK my final vote is for  Light Blue + Light Blue lightened.

**Comment by rhansby** [comment]
I vote for Light Blue + Light Blue (slightly lightened)

**Comment by wp9015362** [comment]
@rhansby & @jklein24 :

As far as I can tell, blue on blue would not be allowed according to the Google Material Design Guidelines, see:

> https://www.google.com/design/spec/style/color.html#color-ui-color-application
> 
> [...] Limit your selection of colors by choosing three hues from the primary palette and one accent color from the secondary palette. [...]
> 
> [...] Don’t use the accent color for app bars or larger areas of color. Avoid using the same color for the floating action button and the background. [...]

As far as I can tell, with secondary palette it means a different color than the primary palette, which is also illustrated in the example there ("Primary - Indigo / Accent - Pink" in the example).

So the accent color has to be a different color altogether AFAICT.

The following would probably look nice:

Theme: [Light](https://github.com/connectbot/connectbot/issues/163)
Primary: Cyan 500 (#00bcd4)
Primary Dark: Cyan 700 (#0097a7)
Accent: Light Blue A400 (#00b0ff) or Light Blue A700 (#0091ea)

Similar to what is shown in the following screenshot from [Amaze File Manager](https://github.com/arpitkh96/AmazeFileManager) (the screenshots shows Light Blue 500 (#03a9f4) and Blue 500 (#2196f3) as accent colors, because that's what Amaze File Manager allows for accent color selection, it does not offer the special accent colors with the "A" in front of the number):

![Image](https://cloud.githubusercontent.com/assets/7558360/9921718/019da244-5ce1-11e5-805d-5cab467893ca.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921716/fc6309a4-5ce0-11e5-9d84-f66956c53813.png)

I think the [light theme](https://github.com/connectbot/connectbot/issues/163) really is key here. It looks much better with a light theme IMHO.

Regards

**Comment by jklein24** [comment]
@wp9015362, your feedback is noted and appreciated, but we've gotten some feedback from some UX folks on our side (including some people on the material design team) who have recommended going with the light blue + light blue (slightly lightened). I at least think we can all agree it's an improvement over the orange :-).

**Comment by rhansby** [comment]
@jklein24 please close this issue.

**Comment by wp9015362** [comment]
> @jklein24 :
> 
> we've gotten some feedback from some UX folks on our side (including some people on the material design team)

If you don't mind answering, I am just wondering:

Is so many Google employees now actively maintaining ConnectBot (judging from the GitHub profiles of @kruton , @khorimoto , @rhansby , @jklein24 ) due to ConnectBot basically being a Google project (for @kruton it say's "Owner")?

> @jklein24 :
> 
> I at least think we can all agree it's an improvement over the orange :-).

Yes we can :yum: .

Regards

**Comment by kruton** [comment]
ConnectBot is a project I started before Google. You can read up on Google's 20% time at various places, though.

**Comment by Tony-il-Capo** [comment]
Hi
Sorry for reopening this but I think this new theme suck. I've installed last release from here to get the last fixes but had to get back to v1.8.7 (fdroid).

My device is a Lt26i (aka Sony Xperia S) and with this theme I can't see/read properly many input text boxes, like url, passphrase, etc... that blue background shadow on those input boxes messes everything.
I have also problems with interface text/items appearing on top of each other, and problems when working on terminal, like keyboard doesn't open (show up).

 Maybe it's related to the small HD screen/high ppi 342??

As for the theme colors, I dislike them very much, but would be ok if we could customize theme colors, within app settings, like many others..

> 

    @jklein24 :

    I at least think we can all agree it's an improvement over the orange :-).

> Yes we can :yum: .

You can only always speak for yourself.
