### ISSUE TITLE
Bad DNS gets cached until total phone reboot

### ISSUE THREAD

**Issue by jidanni** [connectbot/connectbot#348]
Try to connect when wifi accidently off.
DNS gets cached as bad until one reboots entire phone!

**Comment by gittastic** [comment]
What device\android version is that with? Also what build of ConnectBot?

**Comment by jidanni** [comment]
"Latest" connectbot, on Android 4.0.4 mtk6577.

**Comment by kruton** [comment]
I'm not sure ConnectBot could do anything about this since the DNS is cached in netd.

**Comment by gittastic** [comment]
This was a bug\feature fixed somewhere in the Jelly Bean era, if I remember correctly. I used to have similar issues accessing local network resources such as intranet web pages due to DNS caching on my Nexus S. Seems a long time ago now :)

@jidanni As a workaround, I think i put into airplane mode or maybe just toggled the data connection for a moment rather than full reboot.

**Comment by jidanni** [comment]
OK.
