### ISSUE TITLE
Swipe to send page up/down does not work

### ISSUE THREAD

**Issue by trygveaa** [connectbot/connectbot#377]
Even though I have checked "Page up/down gesture" in the settings, swiping on the left side of the screen does not send page up/down keys. It only scrolls the terminal, like the rest of the screen.

This is with the current newest master (c9682d3). The error was introduced by #277, as stated by @rhansby in #270.

**Comment by tsumare** [comment]
This occurs in v1.9.0 which auto-updated onto my Nexus 5x today.  After realizing the gesture no longer worked, I enabled it in settings.  Even after an app exit (and Force Stop), the setting did not take effect.

**Comment by kruton** [comment]
Ah, this only works on pre-Honeycomb devices currently because the `TerminalTextViewOverlay` used for text selection is causing the `onScroll` to [bail out early](https://github.com/connectbot/connectbot/blob/c9682d36ed2460e3045f58823cb37f65fa590d1a/app/src/main/java/org/connectbot/TerminalView.java#L209).

**Comment by tsumare** [comment]
If it ends up being difficult to fix this, I would be more than happy to have a switch to go back to the old behavior regarding scrolling and copy/paste (my naive impression of what TerminalTextViewOverlay is used for).  I use this heavily for irssi and as a result I copy very rarely, but page up and down constantly.
