### ISSUE TITLE
Connection instantly closed on server and hangs on ConnectBot

### ISSUE THREAD

**Issue by Ghosthree3** [connectbot/connectbot#48]
The current Google Play version was working fine except for a small issue where it would not try to reconnect if my connection changed from WiFi to Data or vice versa. I found there were actually new releases elsewhere - like here - so tried updating to those in case it worked. Since updating, when I try to connect the terminal says only "Connecting to address:port via ssh" and hangs forever. I checked my SSH server log on my PC - using Bitvise SSH Server - and it confirms a connection opening and the client sending client version string "SSH-2.0-TrileadSSH2Java_213", then it says the connection was terminated, all in the same second. I tried the version here and all the releases on F-Droid and they all do it.

What can I do to fix the problem? I'll be using the Google Play version until I can get it fixed.

**Comment by j-ed** [comment]
@Ghosthree3 I would recommend to increase the log level on your server to see what the reason for the disconnection is. I realized a similar problem on my server after I had played around with some Cipher and MAC parameters and disabled parameters which ConnectBot required. In my case updating to v1.8.1 solved the problem because the software now supports more secure encryption.

**Comment by kruton** [comment]
This might be fixed in v1.8.3. Could you try that? It is available on Google Play Store or here:
https://github.com/connectbot/connectbot/releases/download/v1.8.3/ConnectBot-v1.8.3.apk

**Comment by Ghosthree3** [comment]
In the new version I am able to connect to my NAS SSH server just fine. However my Windows PC which is running Bitvise SSH Server is still failing. It definitely was working in the old, old version. Now I get the console output

Connecting to ....
Connection Lost
Connecting to ....
Key exchange was not finished, connection is lost
Key exchange was not finished, connection is lost

However it stays 'connected' with a green light and I need to manually disconnect it or it sits in my tray all day.

**Comment by kruton** [comment]
Which version are you using?

**Comment by Ghosthree3** [comment]
Yes, it updated through F-Droid. I checked and it does indeed say 1.8.3.

**Comment by jhgit** [comment]
Now that I updated to 1.8.3 via google play store yesterday (not sure what version it was before), I also get the 'Key exchange was not finished' symptom.  I see it when I connect to an older system (FreeBSD 4 system - no ecdsa host key support).

**Comment by jhgit** [comment]
I started sshd on a FreeBSD 9 system with -o HostKey=/etc/ssh/ssh_host_dsa_key and now I get the 'Key exchange was not finished' symptom.  It seems recent changes to support ecdsa broke old host key formats perhaps?

**Comment by kruton** [comment]
Try the beta v1.8.4 release at https://github.com/connectbot/connectbot/releases/download/v1.8.4/ConnectBot-v1.8.4.apk

**Comment by jhgit** [comment]
Thanks.  That version (1.8.4 beta) fixes the 'Key exchange was not finished' problem.

It also seems to fix another problem I noticed where ConnectBot 1.8.3 was not 'remembering private keys in memory' (the ssh-agent-like feature).  I didn't have a chance to investigate that to see if it had already been reported and to see if I could characterize it better.  But now I don't have to since it seems to work again with the 1.8.4 beta.

**Comment by Ghosthree3** [comment]
The beta version has also fixed my problem, cheers!

**Comment by kruton** [comment]
Great. Closing this issue.
