### ISSUE TITLE
post-login command doesn't execute

### ISSUE THREAD

**Issue by rigid** [connectbot/connectbot#51]
in the latest f-droid build, it seems as if no newline is sent after the post-login command, so the configured command is just printed but not executed.
when enter is pressed, the command gets executed.

**Comment by leonerd** [comment]
Just include a linefeed in the configured command. You can even send multiple commands like this.
For example, I have one that sends two lines; a `cd` to go to the source of a program, then a `./foo` to execute it. Both are terminated with linfeeds.

**Comment by rigid** [comment]
add an LF using copy/paste? i tried "\n" without luck. It would be more intuitive if one LF is appended (since nothing is executed otherwise, even when a command is entered). This would also replicate the behaviour of the native commandline ssh client.
Multiple commands could still be chained using ';' '||' or '&&' etc.
I won't reopen the issue because, in the end, it's a design decision for the devs :)

**Comment by leonerd** [comment]
Just hit the Enter key on the Android keyboard. The text box you configure the command in is multiline capable; it will accept linefeeds just fine.

**Comment by leonerd** [comment]
If anything, the box is just poorly named. It isn't really a "command" to execute on the remote; it's simply a text string that will be sent *as is* to the server on the other side. If there's an interactive shell there it will interpret that as a command. But maybe there's some other program, and this text might navigate options in a text menu, or whatever. We shouldn't always append a linefeed anyway because that might not be appropriate.
