### ISSUE TITLE
Can't select text

### ISSUE THREAD

**Issue by snan** [connectbot/connectbot#532]
Just updated to the new connectbot in F-Droid; I love the _design_ of the new UI for selecting text, but I haven't gotten it to work in practice. I longpress, some letters in the middle of the word are selected. The left handle I can sorta, sometimes, with a couple of tries and restarts move to the correct place. The right handle I can't move at all horizontally. I can drag it down a few lines though, but that doesn't help me (I wanted to copy one very long word).

The old system usually took me a couple of tries and was often frustrating; with the new one I tried for five minutes until giving up and going to my desktop computer.

I love connectbot, it's my most used phone app for sure.

**Comment by laama1** [comment]
I would like to see this new text-selecting feature disabled. Mostly it's annoying. Please add option to disable it.

**Comment by szakharchenko** [comment]
The new system *selects* text correctly (e.g. via double click) but *indicates* selection boundaries incorrectly. This doesn't seem to depend on the font size. I updated because the previous version of copying stopped working (e.g. 5 bytes copied to clipboard when I clearly selected more), only to find the new system just as useless.
